var = input("Digite algo: ")

print("Tipo primitivo: {}".format(type(var)))
print("MAISCULO: {}".format(var.isupper()))
print("MINUSCULO: {}".format(var.islower()))
print("ALFABETICO E NUMERICO: {}".format(var.isalnum()))
print("NUMERICO: {}".format(var.isnumeric()))
print("ALFABETICO: {}".format(var.isalpha()))
print("ASCII: {}".format(var.isascii()))
print("DECIMAL: {}".format(var.isdecimal()))
print("DIGITO: {}".format(var.isdigit()))
print("IDENTIFICADOR: {}".format(var.isidentifier()))
print("ESPACO: {}".format(var.isspace()))
print("PRINTAVEL: {}".format(var.isprintable()))
print("TITULO: {}".format(var.istitle()))
